name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Install CouchDB
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
          echo "deb https://apache.bintray.com/couchdb-deb $(lsb_release -c -s) main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo debconf-set-selections <<-EOF
          	couchdb couchdb/mode select standalone
          	couchdb couchdb/mode seen true
          	couchdb couchdb/bindaddress string 127.0.0.1
          	couchdb couchdb/bindaddress seen true
          	couchdb couchdb/adminpass password
          	couchdb couchdb/adminpass seen true
          	couchdb couchdb/adminpass_again password
          	couchdb couchdb/adminpass_again seen true
          EOF
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes couchdb=2.3.1*
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: |
          git config --global user.email "github@spam.cozycloud.cc"
          git config --global user.name "github actions"
          curl -X PUT http://127.0.0.1:5984/{_users,_replicator}
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          make install
      - name: Lint
        run: make lint
      - name: Unit tests
        run: make tests
