name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Install CouchDB
        run: |
          curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg
          source /etc/os-release
          echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" | sudo tee /etc/apt/sources.list.d/couchdb.list
          sudo apt-get update
          sudo debconf-set-selections <<-EOF
          	couchdb couchdb/mode select standalone
          	couchdb couchdb/mode seen true
          	couchdb couchdb/bindaddress string 127.0.0.1
          	couchdb couchdb/bindaddress seen true
          	couchdb couchdb/adminpass password
          	couchdb couchdb/adminpass seen true
          	couchdb couchdb/adminpass_again password
          	couchdb couchdb/adminpass_again seen true
          EOF
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes couchdb=2.3.1*
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install
        run: |
          git config --global user.email "github@spam.cozycloud.cc"
          git config --global user.name "github actions"
          curl -X PUT http://127.0.0.1:5984/{_users,_replicator}
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          make install
      - name: Lint
        run: make lint
      - name: Unit tests
        run: make tests
